### ISSUE TITLE
data folder structure problem

### ISSUE THREAD

**Issue by kurtwagner19** [fkluger/kitti_horizon#1]
Which raw data should be downloaded? How the data should be fed to script? What folder structure should be given?
the help of the script is not descriptive in this case.

I would be grateful if you can answer

**Comment by kurtwagner19** [comment]
I extracted the date folders inside the raw kiti dataset. the folder names are below

2011_09_28
2011_09_30
2011_09_26
2011_10_03
MyScripts

I created another (MyScripts) folder  and put the scripts in that folder. and running the script inside that folder with command line:
python kitti_horizon_raw.py --path .. --date 2011_09_28

It is giving me an error:
Traceback (most recent call last):
  File "kitti_horizon_raw.py", line 115, in <module>
    all_drives = dataset.get_drive_ids(args.date)
  File "kitti_horizon_raw.py", line 27, in get_drive_ids
    drive = entry.split("_")[-2]
IndexError: list index out of range


Can you please clearly explain the folder structure of the project?
